# Generated by Django 4.2.6 on 2023-10-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("date_submitted", models.DateTimeField(auto_now_add=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "get_latest_by": "date_submitted",
            },
        ),
    ]
